name: IaC Security Gate (Critical Vulnerability)

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  checkov-security-gate:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies (Checkov + jq)
        run: |
          python -m pip install --upgrade pip
          pip install checkov
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Run Checkov and save JSON + TXT reports
        run: |
          checkov -d . -o json --output-file-path checkov-report.json
          checkov -d . -o cli > checkov-report.txt

      - name: Security Gate: Fail if CRITICAL vulnerabilities
        run: |
          CRITICAL_COUNT=0

          if [ -f checkov-report.json ]; then
            # Compter le nombre de vulnérabilités CRITICAL
            CRITICAL_COUNT=$(jq '[.results.failed_checks[] | select(.severity=="CRITICAL")] | length' checkov-report.json)
          fi

          echo "Critical failed checks: ${CRITICAL_COUNT}"

          if [ "${CRITICAL_COUNT}" -gt 0 ]; then
            echo "❌ Vulnerability CRITICAL detected"
            # Affiche les 20 premières vulnérabilités critiques
            jq '.results.failed_checks[] | select(.severity=="CRITICAL") | {file:.file,line:.check_id,check:.check_name,severity:.severity}' checkov-report.json | head -n 20
            exit 1  # fait passer le job en rouge
          else
            echo "✅ No CRITICAL Vulnerability detected"
          fi

      - name: Upload artifacts (reports)
        uses: actions/upload-artifact@v4
        with:
          name: checkov-reports
          path: |
            checkov-report.json
            checkov-report.txt
